name: Bug Report
description: Use this template to report a bug.
title: "[BUG] Issue title"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise description of the bug.
      placeholder: "Describe the bug here."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: "1. Step one\n2. Step two"
    validations:
      required: true
