name: Advanced Issue Form
description: A comprehensive form for submitting detailed issues.
title: "[ISSUE]: Enter a concise issue title here"
labels: []
assignees: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: Select the type of issue you want to report.
      options:
        - label: 🐞 Bug Report
          value: bug
        - label: ✨ Feature Request
          value: enhancement
        - label: 📝 Documentation Improvement
          value: documentation
        - label: ❓ General Question
          value: question
        - label: 📌 Other
          value: other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: Indicate the priority of this issue.
      options:
        - label: 🟥 Critical
          value: critical
        - label: 🟧 High
          value: high
        - label: 🟨 Medium
          value: medium
        - label: 🟩 Low
          value: low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a detailed description of the issue, including what is happening and what you expect to happen.
      placeholder: "Describe your issue in detail here."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for contributing! We will review your issue as soon as possible.
