name: Advanced Issue Form
description: A comprehensive form for submitting detailed issues.
title: "[ISSUE]: Enter a concise issue title here"
labels: []
assignees: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: Select the type of issue you want to report.
      options:
        - "Bug Report 🐞"
        - "Feature Request ✨"
        - "Documentation Improvement 📝"
        - "General Question ❓"
        - "Other 📌"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: Indicate the priority of this issue.
      options:
        - "Critical 🟥"
        - "High 🟧"
        - "Medium 🟨"
        - "Low 🟩"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a detailed description of the issue, including what is happening and what you expect to happen.
      placeholder: "Describe your issue in detail here."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (for bugs)
      description: List the steps to reproduce the issue. If not applicable, write "N/A."
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe the behavior...
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution (for feature requests or enhancements)
      description: Describe the solution or feature you'd like to see.
      placeholder: "Provide details of your proposed solution or enhancement."
    validations:
      required: false

  - type: input
    id: affected_versions
    attributes:
      label: Affected Versions
      description: Specify the versions of the application where the issue occurs. If not applicable, write "N/A."
      placeholder: "e.g., v1.0.0, v1.2.3"
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment Details
      description: Specify the environment where the issue occurs.
      placeholder: "e.g., OS, browser, database, or other relevant details"
    validations:
      required: false

  - type: textarea
    id: file_changed
    attributes:
      label: Files Changed or Affected
      description: Specify the files that are changed or affected by the issue.
      placeholder: "e.g., src/components/Header.js, src/styles/main.css"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any additional context, logs, screenshots, or information that may help diagnose the issue.
      placeholder: "Add any relevant information here."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Thank you for contributing!
        We value your input and will review your issue as soon as possible.
