name: Enhancement Request
description: Use this template to request a feature enhancement.
title: "[ENHANCEMENT] Issue title"
labels: [enhancement]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature.
      placeholder: "Describe the feature request."
    validations:
      required: true
